### ISSUE TITLE
Keyword autocomplete

### ISSUE THREAD

**Issue by bodowinter** [LinguisticData/LinguisticData.github.io#2]
It would be nice if key words are auto completed as one searches for them in the search box.

**Comment by LinguList** [comment]
Okay, one solution is there (potential):

Here's the question:
- http://stackoverflow.com/questions/17277131/auto-complete-with-datatables-jquery-search

here's the example:
- http://output.jsbin.com/orixab/1

Actually nice, but will take time to implement, so we'll put this at the side for the moment. But it is definitely possible.
