### ISSUE TITLE
Tracking how many clicks the website gets

### ISSUE THREAD

**Issue by LinguList** [LinguisticData/LinguisticData.github.io#3]
This was an idea by @bodowinter mentioned before. Now, there is a potential evil solution: we use an iframe that is always opened along with the side. This iframe itself may show the visitor-number, but the good thing is it may be hosted on every website we'd like. So I could also set it up as python on my website, or we write a little php-script that does the same. Dunno if there are better methods for tracking, but I would just use an sqlite3-database and increment the number in there. Counting countries and IP adresses (so that they do not double) is in my opinion going too far. And since the app is only opening once, with the JS, there won't be an overcounting due to multiple opening of the same site.

@bodowinter, how well do you remember PhP, and could you write such a simple tracker (doesn't give out anything but a number) for your webhost? If not, no problem, I know how to do, but you would need to host it, or we host it via my website.

As to the timeline: I won't work on this directly, but it should not take too much time. So in a quiet minute in one or two months, this may be done.

**Comment by widged** [comment]
Content rendered through github pages is not trackable by default (only html+js, php cannot be involved). The usual strategy is to add a 1px image (transparent) somewhere in your file and then have a way to track how many time that image is loaded -- https://growtraffic.com/blog/2016/07/add-tracking-pixel-website

**Comment by LinguList** [comment]
We have a pretty simple content tracker that works, however :) for this reason, we use the php solution, which is not exact, not save, but works well enough for the time being: http://languagegoldmine.com/, using an iframe.
